repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0  # You can specify the version you want
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0  # You can specify the version you want
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971  # You can specify the version you want
    hooks:
      - id: mypy
